diff --git a/Makefile.orig b/Makefile
--- Makefile.orig	2023-04-17 03:07:14.000000000 +0300
+++ Makefile	2023-05-25 16:41:06.018016436 +0300
@@ -43,7 +43,7 @@
 	install -D -m 0644 data/dev.geopjr.Collision.desktop $(PREFIX)/share/applications/dev.geopjr.Collision.desktop
 	install -D -m 0644 data/icons/dev.geopjr.Collision.svg $(PREFIX)/share/icons/hicolor/scalable/apps/dev.geopjr.Collision.svg
 	install -D -m 0644 data/icons/dev.geopjr.Collision-symbolic.svg $(PREFIX)/share/icons/hicolor/symbolic/apps/dev.geopjr.Collision-symbolic.svg
-	gtk-update-icon-cache $(PREFIX)/share/icons/hicolor
+	gtk-update-icon-cache --ignore-theme-index $(PREFIX)/share/icons/hicolor
 	glib-compile-schemas $(PREFIX)/share/glib-2.0/schemas/
 
 uninstall:
---
