.TH ATOMIX 6 "January 30, 2013"
.SH NAME
atomix \- molecule puzzle game
.SH SYNOPSIS
.B atomix
.RI [OPTION...]
.SH DESCRIPTION
\fBAtomix\fP is a Sokoban like puzzle game in which you have to build full molecules,
from simple inorganic ones in the first levels to extremely complex organic ones in
the last levels, out of isolated atoms, which are laying around among walls
and other obstacles on the playfield.

Once you push an atom in a certain direction, it will move until it hits
something that makes it stop, which could be a wall or another atom.
This behaviour is exactly what makes playing it not trivial and, therefore,
fun, as you need to think quite a lot about how to have your molecule
organized.

.SH OPTIONS
.SS "Help Options:"
.TP
\fB\-h, \-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-\-display=DISPLAY\fR
X display to use
